---
- name: Torrent
  tags:
    - torrent
  block:
    - name: Install the docker compose file
      become: true
      template:
        src: "files/docker-compose.yml"
        dest: "{{ docker_dir }}/qbittorrent/docker-compose.yml"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Install torrent creds
      become: true
      copy:
        src: "files/wg0.conf"
        dest: "{{ docker_dir }}/qbittorrent/"
        mode: 0500

    - name: Run compose project
      community.docker.docker_compose_v2:
        project_src: "{{ docker_dir }}/qbittorrent/"
