---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Homeboi"
logo: "logo.png"

header: false
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-photo-film"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.png"
        url: "http://jellyfin.{{ dns_name }}"
        target: "new"
      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        url: "http://radarr.{{ dns_name }}"
        target: "new"
      - name: "Lidarr"
        logo: "assets/icons/lidarr.png"
        url: "http://lidarr.{{ dns_name }}"
        target: "new"
      - name: "Prowlarr"
        logo: "assets/icons/prowlarr.png"
        url: "http://prowlarr.{{ dns_name }}"
        target: "new"

  - name: "Other Apps"
    icon: "fas fa-cloud"
    items:
      - name: "Syncthing"
        logo: "assets/icons/syncthing.png"
        url: "http://syncthing.{{ dns_name }}"
        target: "new"
      - name: "qBittorrent"
        logo: "assets/icons/qBittorrent.svg"
        url: "http://qbit.{{ dns_name }}"
        target: "new"
      - name: "PiKVM"
        logo: "assets/icons/pikvm.png"
        url: "https://pikvm.lan"
        target: "new"

  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "OPNsense"
        logo: "assets/icons/opnsense.png"
        url: "https://192.168.13.1"
        target: "new"
      - name: "UniFi"
        logo: "assets/icons/unifi.svg"
        url: "https://unifi.{{ dns_name }}"
        target: "new"
      - name: "Pi-hole (main)"
        type: PiHole
        apikey: "{{ pihole_apikey }}"
        logo: "assets/icons/pihole.png"
        url: "http://pihole.{{ dns_name }}/admin/"
        endpoint: "http://cors.{{ dns_name }}/http://pihole.{{ dns_name }}/admin/"
        target: "new"
      - name: "Pi-hole (failover)"
        logo: "assets/icons/pihole.png"
        type: PiHole
        apikey: "{{ pihole_apikey }}"
        url: "http://brix.lan:{{ pihole_http }}/admin/"
        endpoint: "http://cors.{{ dns_name }}/http://brix.lan:{{ pihole_http }}/admin/"
        target: "new"

  - name: "Analytics"
    icon: "fas fa-chart-simple"
    items:
      - name: Speedtest Tracker
        type: SpeedtestTracker
        logo: "assets/icons/speedtest.png"
        url: "http://speedtest.{{ dns_name }}"
        target: "new"
      - name: "Grafana"
        logo: "assets/icons/grafana.svg"
        url: "http://grafana.{{ dns_name }}"
        target: "new"
