- name: Homeboi server
  hosts: homeboi
  vars_files:
    - vars/defaults.yml
    - vars/homeboi.yml
    - vars/vault.yml
  roles:
    - role: geerlingguy.security
      become: yes
      tags:
        - security

    - role: geerlingguy.ntp
      become: yes
      tags:
        - ntp

    - role: geerlingguy.node_exporter
      become: yes
      tags:
        - node_exporter
        - monitoring

    - role: roles/docker
      become: yes
      tags:
        - system
        - docker

    - role: roles/system
      become: yes
      tags:
        - system

    - role: roles/backup
      become: yes
      tags:
        - backup

    - role: roles/ups
      become: yes
      tags:
        - ups

    - role: roles/containers
    - role: roles/torrent
    - role: roles/gameservers

    - role: ddns
      become: yes
      tags:
        - ddns
