- name: Initial server setup
  hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.security
      become: yes
      tags:
        - security

    - role: geerlingguy.ntp
      become: yes
      tags:
        - ntp

    - role: geerlingguy.node_exporter
      become: yes
      tags:
        - node_exporter
        - monitoring
        - containers

    - role: roles/system
      become: yes

    - role: roles/containers
