---
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.crypto
  - name: community.docker

roles:
    - name: geerlingguy.security
    - name: geerlingguy.ntp
    - name: geerlingguy.node_exporter
