- name: Wireguard VPN setup
  hosts: vpn
  vars_files:
    - vars/defaults.yml
    - vars/vault.yml
    - vars/vpn.yml
  roles:
    - role: roles/docker
      become: yes

    - role: roles/vpn
      become: yes
      tags:
        - wireguard

    - role: roles/ddns
      tags:
        - ddns
