# keep snapshots on local file system for this many days
keep_snapshot_days = 7
log_file = "~/backups/backup.log"

# the repo prefix in which to back up the data (will make sub-repos for each filesystem backup)
repo_prefix = "~/borg_repos"
# keyfile exports will be here
keyfile_export_dir = "~/.borg_keys"
# file in which to store the passphrase
borg_pass_file = "~/.borg_pass"

# how many of each type of backup to keep
day = 7
week = 4
month = 6

[fs.storage]
fs = "bigboi/storage"

[fs.storage.repos]
borgbase = "{{ storage_borgbase_repo }}"
lilboi = "{{ storage_lilboi_repo }}"

[fs.docker]
fs = "fastboi/docker"
exclude = [
  "wireguard",
  "grafana",
]

[fs.docker.repos]
borgbase = "{{ homeboi_docker_borgbase_repo }}"
lilboi = "{{ homeboi_docker_lilboi_repo }}"

[fs.media]
fs = "bigboi/media"
exclude = [
  "djank_music",
  "downloads",
  "movies",
  "music",
  "tv",
  "youtube",
  ".stfolder",
  ".stignore",
]

[fs.media.repos]
borgbase = "{{ media_borgbase_repo }}"
lilboi = "{{ media_lilboi_repo }}"
