---
- name: Install borg
  tags:
    - backups
  get_url:
    url: https://github.com/borgbackup/borg/releases/download/2.0.0b6/borg-linux64
    dest: /usr/local/bin/borg
    mode: 775

- name: Install python3.11
  tags:
    - backups
  apt:
    name: python3.11
    state: present

- name: Install backup script
  tags:
    - backups
  block:
    - name: Copy config
      template:
        src: files/backups/config.toml
        dest: "/home/{{ username }}/backups/"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Script
      copy:
        src: files/backups/backup.py
        dest: "/home/{{ username }}/backups/backup.py"
        mode: "775"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Install cron
      cron:
        name: "Automated backups"
        job: "/home/{{ username }}/backups/backup.py"
        special_time: daily
        state: present
        user: "{{ username }}"
