services:
  server:
    container_name: tekkit-server
    build: .
    volumes:
      - tekkit:/server
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    restart: unless-stopped

volumes:
  tekkit:
