---
- name: Make sure the Wireguard container is created and running
  docker_container:
    name: "wireguard"
    image: "lscr.io/linuxserver/wireguard"
    pull: yes
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - net_admin
      - sys_module
    state: "started"
    env:
      SERVERURL: "{{ vpn_host }}"
      PEERS: "{{ vpn_peers }}"
      ALLOWEDIPS: "0.0.0.0/0"
      LOG_CONFS: "TRUE"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_dir }}/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped

- name: Wait for peer configs to be generated
  wait_for:
    path: "{{ docker_dir }}/wireguard/config/peer_{{ item }}/peer_{{ item }}.conf"
  loop: "{{ vpn_peers.split(',') }}"
  tags: [never, fetch-creds]

- name: Fetch peer configs to local machine
  fetch:
    src: "{{ docker_dir }}/wireguard/config/peer_{{ item }}/peer_{{ item }}.conf"
    dest: "{{ playbook_dir }}/wireguard/{{ inventory_hostname }}/{{ item }}.conf"
    flat: yes
  loop: "{{ vpn_peers.split(',') }}"
  tags: [never, fetch-creds]

- name: Fetch peer QR codes to local machine
  fetch:
    src: "{{ docker_dir }}/wireguard/config/peer_{{ item }}/peer_{{ item }}.png"
    dest: "{{ playbook_dir }}/wireguard/{{ inventory_hostname }}/{{ item }}.png"
    flat: yes
  loop: "{{ vpn_peers.split(',') }}"
  tags: [never, fetch-creds]
