---
- name: restart prometheus
  docker_container:
    name: prometheus
    restart: yes
    state: started

- name: restart homer
  docker_container:
    name: homer
    restart: yes
    state: started
