---
- name: Nginx proxy
  tags:
    - containers
    - nginx
    - proxy
  block:
    - name: Create nginx folder
      become: true
      file:
        path: "{{ docker_dir }}/nginx"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Config file
      become: true
      template:
        src: "files/nginx.conf"
        dest: "{{ docker_dir }}/nginx/nginx.conf"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Run nginx container
      docker_container:
        name: nginx
        image: nginx
        pull: true
        state: started
        restart: true
        networks:
          - name: host
        volumes:
          - "{{ docker_dir }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        restart_policy: unless-stopped

- name: Watchtower
  tags:
    - containers
    - watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped

- name: CORS container
  tags:
    - containers
    - cors
  docker_container:
    name: cors
    pull: true
    image: imjacobclark/cors-container
    ports:
      - "127.0.0.1:{{ cors_http }}:3000"
    restart_policy: unless-stopped

- name: Homer
  tags:
    - containers
    - homer
  block:
    - name: Create and chmod folders
      become: true
      file:
        path: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ docker_dir }}/homer"

    - name: Homer icons
      copy:
        src: "files/homer/icons"
        dest: "{{ docker_dir }}/homer/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      notify: restart homer

    - name: Homer config
      template:
        src: "files/homer/config.yml"
        dest: "{{ docker_dir }}/homer/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Make sure the Homer container is created and running
      docker_container:
        name: homer
        image: "b4bz/homer"
        pull: true
        state: started
        ports:
          - "127.0.0.1:{{ homer_http }}:8080"
        user: "{{ uid }}"
        volumes:
          - "{{ docker_dir }}/homer:/www/assets"
        restart_policy: unless-stopped

- name: Syncthing
  tags:
    - containers
    - syncthing
  docker_container:
    name: syncthing
    image: "syncthing/syncthing"
    pull: true
    state: started
    env:
      "PUID": "1000"
      "PGID": "1000"
    networks:
      - name: host
    volumes:
      - "{{ docker_dir }}/syncthing:/var/syncthing"
      - "/growingboi/storage/sync:/sync"
      - "/growingboi/media/:/media"
    restart_policy: unless-stopped

- import_tasks: analytics.yml
- import_tasks: media.yml
- import_tasks: network.yml
