---
- name: Watchtower
  tags:
    - containers
    - watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped

- name: CORS container
  tags:
    - containers
    - cors
  docker_container:
    name: cors
    pull: true
    image: imjacobclark/cors-container
    ports:
      - "{{ cors_http }}:3000"
    restart_policy: unless-stopped

- name: Jellyfin
  tags:
    - containers
    - jellyfin
  block:
    - name: Create and chmod folders
      become: true
      file:
        path: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        mode: 0755
        recurse: true
      with_items:
        - "{{ docker_dir }}/jellyfin/config"
        - "{{ docker_dir }}/jellyfin/cache"

    - name: Make sure the Jellyfin container is created and running
      docker_container:
        name: jellyfin
        image: "jellyfin/jellyfin"
        pull: true
        state: started
        networks:
          - name: host
        user: "{{ uid }}"
        volumes:
          - "{{ docker_dir }}/jellyfin/config:/config"
          - "{{ docker_dir }}/jellyfin/cache:/cache"
          - "/growingboi/media:/media"
        restart_policy: unless-stopped
        runtime: nvidia

- name: Homer
  tags:
    - containers
    - homer
  block:
    - name: Create and chmod folders
      become: true
      file:
        path: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        mode: 0755
        recurse: true
      with_items:
        - "{{ docker_dir }}/homer"

    - name: Homer icons
      copy:
        src: "files/homer/icons"
        dest: "{{ docker_dir }}/homer/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      notify: restart homer

    - name: Homer config
      template:
        src: "files/homer/config.yml"
        dest: "{{ docker_dir }}/homer/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Make sure the Homer container is created and running
      docker_container:
        name: homer
        image: "b4bz/homer"
        pull: true
        state: started
        ports:
          - "{{ homer_http }}:8080"
        user: "{{ uid }}"
        volumes:
          - "{{ docker_dir }}/homer:/www/assets"
        restart_policy: unless-stopped

- name: Syncthing
  tags:
    - containers
    - syncthing
  docker_container:
    name: syncthing
    image: "syncthing/syncthing"
    pull: true
    state: started
    env:
      "PUID": "1000"
      "PGID": "1000"
    networks:
      - name: host
    volumes:
      - "/growingboi/storage/syncthing:/var/syncthing"
    restart_policy: unless-stopped

- import_tasks: analytics.yml
- import_tasks: network.yml
