---
- name: Traefik proxy
  tags:
    - containers
    - traefik
    - proxy
  block:
    - name: Create traefik folder
      become: true
      file:
        path: "{{ docker_dir }}/traefik"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Create acme.json
      file:
        path: "{{ docker_dir }}/traefik/acme.json"
        state: touch
        modification_time: preserve
        access_time: preserve
        mode: 0600

    - name: Template config file
      template:
        src: "files/traefik/traefik.yml"
        dest: "{{ docker_dir }}/traefik/traefik.yml"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Template compose file
      template:
        src: "files/traefik/docker-compose.yml"
        dest: "{{ docker_dir }}/traefik/docker-compose.yml"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Run traefik compose
      community.docker.docker_compose_v2:
        project_src: "{{ docker_dir }}/traefik"

- name: Watchtower
  tags:
    - containers
    - watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped

- name: Homepage
  tags:
    - containers
    - homepage
  block:
    - name: Create and chmod folders
      become: true
      file:
        path: "{{ docker_dir }}/homepage"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        mode: 0755

    - name: Homepage images
      synchronize:
        src: "files/homepage/images"
        dest: "{{ docker_dir }}/homepage/"
      notify: restart homepage

    - name: Homepage config
      template:
        src: "{{ item }}"
        dest: "{{ docker_dir }}/homepage/config/"
        owner: "{{ username }}"
        group: "{{ username }}"
      with_fileglob:
        - "files/homepage/config/*.yaml"

    - name: Make sure the Homepage container is created and running
      docker_container:
        name: homepage
        image: "ghcr.io/gethomepage/homepage"
        pull: true
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "{{ uid }}"
          PGID: "{{ guid }}"
          HOMEPAGE_ALLOWED_HOSTS: "{{ dns_name }}"
        volumes:
          - "{{ docker_dir }}/homepage/config:/app/config"
          - "{{ docker_dir }}/homepage/images:/app/public/images"
        networks:
          - name: proxy
        labels:
          traefik.enable: "true"
          traefik.http.routers.homepage.rule: "Host(`{{ dns_name }}`)"
          traefik.http.routers.homepage.entrypoints: "https"
          traefik.http.routers.homepage.tls.certresolver: "godaddy"

- name: Syncthing
  tags:
    - containers
    - syncthing
  docker_container:
    name: syncthing
    image: "syncthing/syncthing"
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      "PUID": "1000"
      "PGID": "1000"
    networks:
      - name: host
    volumes:
      - "{{ docker_dir }}/syncthing:/var/syncthing"
      - "/bigboi/storage/syncs:/syncs"
      - "/bigboi/media/:/media"
    labels:
      traefik.enable: "true"
      traefik.http.routers.syncthing.rule: "Host(`syncthing.{{ dns_name }}`)"
      traefik.http.services.syncthing.loadbalancer.server.port: "8384"
      traefik.http.routers.syncthing.entrypoints: "https"
      traefik.http.routers.syncthing.tls.certresolver: "godaddy"

- name: Run IT Tools
  tags:
    - containers
    - it-tools
  docker_container:
    name: it-tools
    image: corentinth/it-tools
    state: started
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.it-tools.rule: "Host(`it-tools.{{ dns_name }}`)"
      traefik.http.routers.it-tools.entrypoints: "https"
      traefik.http.routers.it-tools.tls.certresolver: "godaddy"

- import_tasks: analytics.yml
- import_tasks: media.yml
- import_tasks: network.yml
