---
- name: Check if docker is installed
  tags:
    - docker
    - nvidia-docker
  package_facts:
    manager: "auto"

- name: Install docker
  when: "'docker-ce' not in ansible_facts.packages"
  tags: docker
  block:
    - name: Install requirements to install docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - docker-compose

- name: Add user '{{ username }}' to docker group
  tags: docker
  user:
    name: '{{ username }}'
    groups: docker
    append: yes


- name: Nvidia Docker
  tags: nvidia-docker
  when:
    - "'nvidia-docker2' not in ansible_facts.packages"
    - "enable_nvidia_docker | default(False)"
  block:
    - name: Add nvidia-docker GPG key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: Add nvidia-docker repo
      template:
        src: files/libnvidia-container.list.j2
        dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
        mode: '0644'

    - name: Install nvidia-docker
      apt:
        name: nvidia-docker2
        state: latest
        update_cache: yes

    - name: restart docker
      systemd:
        name: docker
        daemon_reload: yes
        state: restarted
