---
- name: GoDaddy DDNS
  tags:
    - godaddy
    - ddns
  become: true
  block:
    - name: Ensure cron installed
      apt:
        name: cron
        state: latest

    - name: Install the DDNS script
      template:
        src: "files/gdddns.j2"
        dest: "/usr/local/bin/gdddns.sh"
        mode: 0500

    - name: Create cronjob
      cron:
        name: GoDaddy DDNS
        user: root
        minute: "*/10"
        job: "/usr/local/bin/gdddns.sh > /dev/null"
